### ISSUE TITLE
更新melpa包

### ISSUE THREAD

**Issue by bennyyip** [manateelazycat/sdcv#11]
https://melpa.org/#/sdcv 指向了这个fork： https://github.com/stardiviner/sdcv.el/
<del>使用 `(require 'sdcv)` 会装上melpa上的包而不是这个。
或者考虑更新文档的安装方式？</del>

对 Emacs 的包管理机制理解有误，sorry。

**Comment by manateelazycat** [comment]
我不喜欢sdcv
