### ISSUE TITLE
unicode parsing problem?

### ISSUE THREAD

**Issue by logexp1** [manateelazycat/sdcv#12]
My emacs buffer or posframe does not correctly display special characters or symbols (ex. '\u2022' instead of bullet symbol) unlike in the picture from your README.
When I run sdcv command from the shell inside emacs, it does print correctly. What might be wrong? any suggestion?
Thanks

**Comment by manateelazycat** [comment]
sdcv.el use LANG=zh_CN.UTF-8 before call sdcv program.

Which LANG set by your system?

**Comment by logexp1** [comment]
That was the problem! Thanks!
