### ISSUE TITLE
sdcv-search-pointer returns empty *SDCV* buffer

### ISSUE THREAD

**Issue by showgood** [manateelazycat/sdcv#13]
I use latest sdcv.el. My Emacs config is DOOM emacs and emacs version is 28.

`sdcv-search-pointer+` works properly and shows a childframe with some content, but `sdcv-search-pointer` shows an empty *SDCV* buffer, not sure why..

**Comment by manateelazycat** [comment]
sdcv-search-point+ use sdcv-dictionary-simple-list
sdcv-search-point use sdcv-dictionary-complete-list

Did you set sdcv-dictionary-complete-list ?

**Comment by showgood** [comment]
I have set it and run help on this variable shows below info:
```
sdcv-dictionary-complete-list is a variable defined in sdcv.el.

Value
("懒虫简明英汉词典" "懒虫简明汉英词典" "KDic11万英汉词典" "牛津英汉双解美化版")
```

**Comment by manateelazycat** [comment]
你检查了这些词典都存在吗？你可以先运行一下 sdcv-check 命令。

**Comment by showgood** [comment]
都存在，sdcv-check返回结果：

The dictionary’s settings look correct, sdcv should work as expected.

**Comment by showgood** [comment]
我没有安装stardict， 因为homebrew没有这个formula，但是感觉sdcv应该就够了，不知道这个是不是原因？

**Comment by manateelazycat** [comment]
如果你 sdcv-search-pointer+ 可以工作，sdv-search-pointer 也可以工作，这两个函数是同一个内部原理。

**Comment by showgood** [comment]
不知道是不是doom emacs的问题。。

**Comment by manateelazycat** [comment]
你可以先用 emacs -Q 做一个对比测试
