### ISSUE TITLE
Display wrong encode characters

### ISSUE THREAD

**Issue by vuquangtam** [manateelazycat/sdcv#15]
Long time ago i use it normally. I've just upgraded to new version recently, characters are encoded wrongly as image below
![Screenshot from 2020-06-09 15-04-33](https://user-images.githubusercontent.com/6467819/84122643-f3adec00-aa62-11ea-99bb-121833d95611.png)
I searched commit log and saw the encode was fixed to zh_CN. I try changing it to en_US and it works like a charm.
Can you add an option for customize this LANG env.

**Comment by manateelazycat** [comment]
Done https://github.com/manateelazycat/sdcv/commit/c96b8062c0fc334c0693b4c6d833c1320aeb85bf
