### ISSUE TITLE
有无可能增加返回上一页的功能

### ISSUE THREAD

**Issue by xiangsheng** [manateelazycat/sdcv#16]
有时候查询全英文词典，会在词条的解释中出现不认识的单词，此时如果按`p`去查询这个不认识的单词的话，阅读完这个不认识词的解释后，如果有类似返回上一页的功能，返回原来的词条就显得非常方便，有无可能增加类似的功能呢？

**Comment by manateelazycat** [comment]
欢迎编写新的补丁，sdcv现在满足我个人所有需求，我乐意接受这个功能的补丁，谢谢你的建议

**Comment by manateelazycat** [comment]
这个建议自己写一个补丁，记录每次查询的单词，再写个函数显示上次查询的单词。
建议加到自己的自定义函数中，加到 sdcv 太奇怪了。
