### ISSUE TITLE
sdcv-pick-word: Invalid function: return

### ISSUE THREAD

**Issue by emacsbliss** [manateelazycat/sdcv#18]
Got this error when running `sdcv-search-pointer+`.

Running on MacOS,  emacs version:

```
GNU Emacs 28.0.50 (build 1, x86_64-apple-darwin19.5.0, NS appkit-1894.50 Version 10.15.5 (Build 19F101)) of 2020-10-16
```

**Comment by manateelazycat** [comment]
error details ？

**Comment by emacsbliss** [comment]
unfortunately that's all the error I can see. even turning on debug-on-error doesn't really produce more detail..

**Comment by manateelazycat** [comment]
I believe this issue is intro by https://github.com/manateelazycat/sdcv/commit/7646395c27bb8b09b1623505e5a190d143a91069

Can you test newest version?

**Comment by emacsbliss** [comment]
latest version works! thanks a lot!
