### ISSUE TITLE
sdcv failed to work on Ubuntu 20.04.

### ISSUE THREAD

**Issue by hongyi-zhao** [manateelazycat/sdcv#21]
On Ubuntu 20.04, I installed the latest sdcv and added some dictionaries as shown below: 

```
werner@X10DAi:~$ sdcv -v
Console version of Stardict, version 0.5.3
werner@X10DAi:~$ sdcv -l
Dictionary's name   Word count
懒虫简明英汉词典    452185
Webster's Third New International Dictionary, Unabridged (En-En)    296190
```
The Emacs configuration for sdcv is as follows:
```emacs-lisp
(use-package sdcv
  :demand t
  :straight (:host github :repo "manateelazycat/sdcv")
  :config
  ;https://github.com/manateelazycat/sdcv#configuration
  (setq ;sdcv-say-word-p t        ;say word after translation
        sdcv-dictionary-data-dir "~/.stardict/dic" ;setup directory of stardict dictionary
        sdcv-dictionary-simple-list    ;setup dictionary list for simple search
        '("Webster's Third New International Dictionary, Unabridged (En-En)"
          "懒虫简明英汉词典"
          )

        sdcv-dictionary-complete-list ;setup dictionary list for complete search
        '("Webster's Third New International Dictionary, Unabridged (En-En)"
          "懒虫简明英汉词典"
        )))
```
With the point on a word, say, "you", I issue the command `M-x sdcv-search-point RET', but nothing returned:

![image](https://user-images.githubusercontent.com/11155854/126864040-9710a943-7865-4c85-ac34-b5de4e7c2f51.png)

Any hints for this problem?

Regards,
HY

**Comment by ghost** [comment]
Try `M-x sdcv-check`, the dictionary name might be wrong.

**Comment by hongyi-zhao** [comment]
> Try `M-x sdcv-check`, the dictionary name might be wrong. 

`The dictionary’s settings look correct, sdcv should work as expected.`

And [emacs-sdcv](https://github.com/gucong/emacs-sdcv)  works smoothly using the same dictionaries setting with the following configuration:

```emacs-lisp
(use-package sdcv-mode
  :demand t
  :straight (:host github :repo "gucong/emacs-sdcv")
  :config
  (setq sdcv-dictionary-list 
        '("Webster's Third New International Dictionary, Unabridged (En-En)"
          "懒虫简明英汉词典")))
```

![image](https://user-images.githubusercontent.com/11155854/126948510-ca8290df-f9d2-4f17-a702-5c8e6ada1ab1.png)

But [emacs-sdcv](https://github.com/gucong/emacs-sdcv) can only return the query results from the first dictionary. I still can't figure out the fix.

**Comment by manateelazycat** [comment]
Please use sdcv-check, and read message of sdcv-check.

**Comment by hongyi-zhao** [comment]
![image](https://user-images.githubusercontent.com/11155854/128617389-b9f8ec66-e909-47ea-a8e5-1097965e5772.png)

![image](https://user-images.githubusercontent.com/11155854/128617359-a3273e0d-0be0-4fa1-90cd-fe78d9ddc5c8.png)

**Comment by ghost** [comment]
@hongyi-zhao This is wired... But I believe that sdcv.el need a explicite `require` to work, dose the `:ensure` keyword provided by use-package guarantee this ? If not, try replace the `:ensure t` statement with `:init (require 'sdcv)`

**Comment by hongyi-zhao** [comment]
No, all the above tricks can't fix the problem. But [sdcv.el](https://github.com/stardiviner/sdcv.el) works smoothly with the following configuration:

```emacs-lisp
;https://github.com/stardiviner/sdcv.el
(use-package showtip)
(use-package sdcv
  :demand t
  :straight (stardiviner-sdcv\.el :local-repo "stardiviner-sdcv.el" :host github :repo "stardiviner/sdcv.el")
  :config
  (setq ; This version doesn't have the following options:
        ;sdcv-say-word-p t        ;say word after translation
        ;sdcv-dictionary-data-dir "~/.stardict/dic" ;setup directory of stardict dictionary
       
        ; Below are the valid options:
        ; sdcv-dictionary-simple-list    ;setup dictionary list for simple search
        ; '("Webster's Third New International Dictionary, Unabridged (En-En)"
        ;   "懒虫简明英汉词典")

        ;The query results are returned in the reverse order of the dictionaries that appear in the list.
        sdcv-dictionary-complete-list ;setup dictionary list for complete search
        (nreverse '("Webster's Third New International Dictionary, Unabridged (En-En)"
                    "Oxford English Dictionary 2nd Ed. P1"
                    "Oxford English Dictionary 2nd Ed. P2")))
  :bind
  ("C-x s" . sdcv-search-pointer))
```

**Comment by Mercurius-Lee** [comment]
> No, all the above tricks can't fix the problem. But [sdcv.el](https://github.com/stardiviner/sdcv.el) works smoothly with the following configuration:
> 
> ```emacs-lisp
> ;https://github.com/stardiviner/sdcv.el
> (use-package showtip)
> (use-package sdcv
>   :demand t
>   :straight (stardiviner-sdcv\.el :local-repo "stardiviner-sdcv.el" :host github :repo "stardiviner/sdcv.el")
>   :config
>   (setq ; This version doesn't have the following options:
>         ;sdcv-say-word-p t        ;say word after translation
>         ;sdcv-dictionary-data-dir "~/.stardict/dic" ;setup directory of stardict dictionary
>        
>         ; Below are the valid options:
>         ; sdcv-dictionary-simple-list    ;setup dictionary list for simple search
>         ; '("Webster's Third New International Dictionary, Unabridged (En-En)"
>         ;   "懒虫简明英汉词典")
> 
>         ;The query results are returned in the reverse order of the dictionaries that appear in the list.
>         sdcv-dictionary-complete-list ;setup dictionary list for complete search
>         (nreverse '("Webster's Third New International Dictionary, Unabridged (En-En)"
>                     "Oxford English Dictionary 2nd Ed. P1"
>                     "Oxford English Dictionary 2nd Ed. P2")))
>   :bind
>   ("C-x s" . sdcv-search-pointer))
> ```

I also guessed that the " sdcv-check " function had a bug ,
 since I used the stardiviner repo without the sdcv-check and
 it looks well.

**Comment by X-Shine** [comment]
@hongyi-zhao hello! I met the same problem today and my config is simliar to yours. Then I replace ~ to my absolute home path and it works. Do you replace ~ with your absolute home path? Sorry for my poor english.

**Comment by hongyi-zhao** [comment]
You're right. The following configuration works:
```emacs-lisp
sdcv-dictionary-data-dir (expand-file-name "~/.stardict/dic")
```
