### ISSUE TITLE
Suggestion: change outline to ewoc

### ISSUE THREAD

**Issue by xFA25E** [manateelazycat/sdcv#27]
I noticed that `sdcv` command provides a `--json` flag. I think that we could drop **outline** and make a better and more extensible interface with **ewoc** library. 

Since, there is already a **json** package, we could use it to parse json output of sdcv. This will be much easier to work with and would eliminate problems with regexp matching of heading. Sometimes, font-locking fails to recognize heading. Like here:

![sdcv font lock failure](https://raw.githubusercontent.com/xFA25E/images/main/sdcvfailfontlock.png)

I can submit a PR

Of course, this means that a lot of code should be rewritten, but the functionality would remain the same.

**Comment by manateelazycat** [comment]
PR are welcome!
