### ISSUE TITLE
辞典文件夹路径问题

### ISSUE THREAD

**Issue by SouthFox-D** [manateelazycat/sdcv#35]
系统：`manjaro`
Emacs 版本：`28.1`
配置：`Doom Emacs`

之前是直接用
```Emacs lisp
(package! sdcv)
```
进行安装的，发现是非常久的远古版本但还是能正常使用，之后用
```Emacs lisp
(package! sdcv
  :recipe (:host github :repo "manateelazycat/sdcv"))
```
安装新版，发现无法正常使用，报错辞典文件夹不存在，参照 [这个问答](https://github.com/manateelazycat/sdcv/issues/21#issuecomment-918124441) 把文件夹路径改成
```Emacs lisp
(setq sdcv-dictionary-data-dir (expand-file-name "~/.stardict/dic"))
```
才能正常工作……

**Comment by manateelazycat** [comment]
sdcv 的作者是我， 但是 melpa 的版本不是我上传维护的，正常的 sdcv 必须要让用户设置字典目录， README写的很清楚。

这个不是 bug, 而是两个包的设置不一样。

**Comment by SouthFox-D** [comment]
> sdcv 的作者是我， 但是 melpa 的版本不是我上传维护的，正常的 sdcv 必须要让用户设置字典目录， README写的很清楚。
> 
> 这个不是 bug, 而是两个包的设置不一样。

抱歉我可能没讲清楚，之前安装我也是参照了 `README` 了的，当时设置的是：

```Emacs lisp
(setq sdcv-dictionary-data-dir "~/.stardict/dic")
```
但这样设置会报错：
![image](https://user-images.githubusercontent.com/58982705/169227566-c9705049-7e5c-43e3-9350-c48b22a64e06.png)

**Comment by manateelazycat** [comment]
> > sdcv 的作者是我， 但是 melpa 的版本不是我上传维护的，正常的 sdcv 必须要让用户设置字典目录， README写的很清楚。
> > 这个不是 bug, 而是两个包的设置不一样。
> 
> 抱歉我可能没讲清楚，之前安装我也是参照了 `README` 了的，当时设置的是：
> 
> ```emacs-lisp
> (setq sdcv-dictionary-data-dir "~/.stardict/dic")
> ```
> 
> 但这样设置会报错： ![image](https://user-images.githubusercontent.com/58982705/169227566-c9705049-7e5c-43e3-9350-c48b22a64e06.png)

好的，我明白了，我把README改一下，谢谢反馈

**Comment by lemyx** [comment]
> > sdcv 的作者是我， 但是 melpa 的版本不是我上传维护的，正常的 sdcv 必须要让用户设置字典目录， README写的很清楚。
> > 这个不是 bug, 而是两个包的设置不一样。
> 
> 抱歉我可能没讲清楚，之前安装我也是参照了 `README` 了的，当时设置的是：
> 
> ```emacs-lisp
> (setq sdcv-dictionary-data-dir "~/.stardict/dic")
> ```
> 
> 但这样设置会报错： ![image](https://user-images.githubusercontent.com/58982705/169227566-c9705049-7e5c-43e3-9350-c48b22a64e06.png)

确实如果直接设置
```
(setq sdcv-dictionary-data-dir "~/.stardict/dic")
```
这种方式不work
```
(setq sdcv-dictionary-data-dir (expand-file-name "~/.stardict/dic"))
```
这样就行了。
