### ISSUE TITLE
brew install stardict ; stardict 没有了

### ISSUE THREAD

**Issue by xiaozhu1337** [manateelazycat/sdcv#9]
brew install stardict 
已经安装不了stardict了,sdcv倒是能安装

**Comment by manateelazycat** [comment]
sdcv 只是 stardict 的命令行接口，翻译主要还是 stardict 来发挥作用吧。

stardict 的安装自己想办法吧，建议向 brew 去反馈这个问题。

**Comment by xiaozhu1337** [comment]
话说,大佬你这个插件不是只用了stardict的词典吗?为啥还需要stardict程序

**Comment by manateelazycat** [comment]
> 话说,大佬你这个插件不是只用了stardict的词典吗?为啥还需要stardict程序

词典只是数据格式啊，需要 stardict 才能解析成可以阅读的文本啊

**Comment by Eason0210** [comment]
@xiaozhu1337  Brew 现在确实是没法装了，你可以到官网上下压缩包解压就可以用了。
[http://stardict-4.sourceforge.net/](url)    我下的3.0.5 beta1 版本 可以正常使用。
